spring.application.name=KTUVotingapp

# Local database ONLY (your laptop)
spring.datasource.url=jdbc:postgresql://localhost:5432/ktuvoting
spring.datasource.username=postgres
spring.datasource.password=kkkkk11111
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# Static Resources Configuration
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=3600
spring.mvc.static-path-pattern=/**


